name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v4
      #   with:
      #     images: |
      #       ghcr.io/${{ github.repository }}/main

      - name: Docker pull latest images
        run: docker pull ghcr.io/${{ github.repository }}/main:latest

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile
          push: true
          # tags: ${{ steps.meta.outputs.tags }}
          # labels: ${{ steps.meta.outputs.labels }}
          # platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}/main:${{ github.ref_name }}-${{ github.run_id }},
            ghcr.io/${{ github.repository }}/main:latest

  deploy:
    runs-on: self-hosted
    needs: build
    if: ${{ needs.build.result == 'success' }}
    steps:
      - name: Checkout yaml file
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            docker-compose.yml
          sparse-checkout-cone-mode: false

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy using Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d
        env:
          IMAGE: ghcr.io/${{ github.repository }}/main:${{ github.ref_name }}-${{ github.run_id }}
          REGISTRY_USERNAME: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
